### ISSUE TITLE
Create a plan for loading a sample using Austin

### ISSUE THREAD

**Issue by canismarko** [spc-group/haven#158]

**Comment by canismarko** [comment]
Based on in person discussion with @yannachen:

The steps should be:

1. Record the current aerotech positions
2. Move the aerotech to the loading position (how do we decide where that is?)
3. Set the ``sampleN:load`` PV.
4. Return the aerotech to its original position

We could maybe use the motor positions functionality already built into Haven?

**Comment by canismarko** [comment]
@yannachen we merged this in, right? Can this issue be closed?

**Comment by yannachen** [comment]
Yes, it is done. Please close it.
