### ISSUE TITLE
Make a list_motors() function

### ISSUE THREAD

**Issue by canismarko** [spc-group/haven#18]
Right now, the list of motor names gets printed during ``load_instrument()``, but it would nice to have a way to just list all the motor names. Maybe it goes in as a method of the instrument registry? Or else as a stand-alone function.

Regardless, it should probably present the same interface as the ``list_motor_positions()`` to stay DRY.

**Comment by canismarko** [comment]
@yannachen This might be related to what you mentioned the other day. Maybe we have two functions:

1. ``list_motor_positions()`` --> lists motor positions previously saved in the database.
2. ``list_motors()`` --> shows the current motors and their positions.

(1) is done, and (2) still needs to be written. We could also rename them to be more clear, if you like.

Thoughts?

**Comment by yannachen** [comment]
Yes, will do it.


Sincerely,

Yanna

**Comment by canismarko** [comment]
@yannachen Thanks! I was mostly asking if what I described made sense. Of course you're welcome to do it if you want. I will assign it to you, but you can unassign if you decide not to do it.

**Comment by canismarko** [comment]
Fix: 82090fe9c5dee134805230d7cd90d48d6f4980ac
