### ISSUE TITLE
issues when step size is bigger than stop point in xafs_scan

### ISSUE THREAD

**Issue by Cathyhjj** [spc-group/haven#197]
Observed issues in xafs_scan, when step size is bigger than stop point. 
- To be discussed on Tuesday

**Comment by canismarko** [comment]
For example: 

start: 0
step: 50
end: 70

Which of the following is correct:

1. [0, 50]
2. [0, 50, 70]
3. [0, 50, 100]

**Comment by canismarko** [comment]
Consensus from SKD/MAS/CJS was option 1.

**Comment by canismarko** [comment]
Possible fix: https://github.com/spc-group/haven/commit/d48328cf57e4a8656355bf33b8afe3483651f543

**Comment by Cathyhjj** [comment]
solved by Mark using np.linspace
