### ISSUE TITLE
Add "is_standard" as standard metadata to the xafs/energy scans

### ISSUE THREAD

**Issue by canismarko** [spc-group/haven#201]
We want a way to keep track of whether a scan should be included in our list of standards that have been run previously.

My thought was we include a new boolean metadatum in each scan: ``is_standard``.

We should add this as a checkbox to the xafs_scan plan window in Firefly.

We could also consider adding a parameter ``is_standard=None`` to the ``xafs_scan()`` and ``energy_scan()`` plans to make it easier for us to remember what the metadatum key should be, but not sure this is necessary.

@Cathyhjj Do you think this should be part of the planwindows PR, or a separate feature?

**Comment by canismarko** [comment]
We should also add a way to view standards from the run_browser filters.

**Comment by canismarko** [comment]
@Cathyhjj I think this is done, right?

**Comment by Cathyhjj** [comment]
You had a comment "We should also add a way to view standards from the run_browser filters." 

I am not sure whether this is done, that's why I didn't close this ticket.

**Comment by canismarko** [comment]
Ah right. I'm going to close this and make that a separate issue.
