### ISSUE TITLE
Usability improvements to the XAFS scan window

### ISSUE THREAD

**Issue by canismarko** [spc-group/haven#207]
- [x] Box for sample notes (larger than just sample name)
- [x] Estimated scan time based on exposure times
- [x] Repeated scans
- [x] Add tooltips to widgets
- [x] Modal dialog when selecting ``is_standard`` to notify that data may be public
- [x] add spacer to XAFS_scan window

**Comment by Cathyhjj** [comment]
- [ ] Change timeEdit into labels
- [ ] time/scan & total exposure scans including time of multiple scans
- [ ] Scan. num --> num. of scans
- [ ] yes/no options for is_standard pop up window
