### ISSUE TITLE
Give each row of grid scan window its own num_pts spin box

### ISSUE THREAD

**Issue by canismarko** [spc-group/haven#231]

**Comment by Cathyhjj** [comment]
another bug, before disable the last snake, make sure it's unchecked

**Comment by Cathyhjj** [comment]
move motor, doesn't check whether metadata's valid values

**Comment by Cathyhjj** [comment]
> another bug, before disable the last snake, make sure it's unchecked

Fixed

**Comment by Cathyhjj** [comment]
> _No description provided._

Fixed
