### ISSUE TITLE
XAFS_scan window queue button

### ISSUE THREAD

**Issue by Cathyhjj** [spc-group/haven#283]
**Describe the bug**
XAFS_scan window in Firefly's queue button should change status to "add to queue" instead of "run"; the other windows' queue button status were changed but not the XAFS_scan window. Even though it showed "run", it actually did add to the queue.

**To Reproduce**
1. Open Firefly XAFS_scan on the LERIX computer (ssh into 25idcuser@microprobe firefly though)
2. Check/uncheck autostart, and compare with other windows

**Expected behavior**
The queue button status should be consistent with other plan winodws

**Comment by canismarko** [comment]
I think this might just be a question of changing the text of the button. Are you able to give it a look, @Cathyhjj?

**Comment by Cathyhjj** [comment]
fixed in #290
