### ISSUE TITLE
auto gain

### ISSUE THREAD

**Issue by Cathyhjj** [spc-group/haven#284]
I remembered you had a feature to let ion-chambers adjust their gain automatically during a scan? 
How to use that feature?

**Comment by Cathyhjj** [comment]
Or maybe another way:
can the ion chamber gain value changed in the queue? Could it be used in the move_motor plan?

**Comment by canismarko** [comment]
> How to use that feature?

Just run the ``auto_gain`` plan. For example:

```python
RE(haven.plans.auto_gain([I0, It, ...]))
```

It can also be run in Firefly through the voltmeters window. Select which ion chambers to include with the checkboxes labeled "Auto-gain", and click the "auto-gain button at the bottom to add it to the queue:

![image](https://github.com/user-attachments/assets/bc5ddf10-a242-498e-bae2-08047710a933)


> Or maybe another way:
> can the ion chamber gain value changed in the queue? Could it be used in the move_motor plan?

Yes, that would also work. The preamp is a child of the ion chamber, so you should be able to find it in the selector (and don't forget the offset).

![image](https://github.com/user-attachments/assets/798a951b-56b6-479d-bb9e-67f43f0731c7)

**Comment by Cathyhjj** [comment]
I don't think we want to change the gain during a scan, changing in queue is great! Thanks!

**Comment by canismarko** [comment]
Great, we good then? Want to close this issue?

**Comment by Cathyhjj** [comment]
Sure!

Juanjuan Huang
