### ISSUE TITLE
Energy scan sample_name metadata not getting into the database

### ISSUE THREAD

**Issue by canismarko** [spc-group/haven#287]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by canismarko** [comment]
@Cathyhjj I added a test for making sure the xafs_scan and energy_scan plans handle metadata properly on the xafs_metadata branch. Would you please fix the metadata so that is uses "sample_name" instead of "sample".

**Comment by Cathyhjj** [comment]
changed and created a PR @canismarko
