### ISSUE TITLE
Run button gets disabled from time to time

### ISSUE THREAD

**Issue by Cathyhjj** [spc-group/haven#299]
**Describe the bug**
Sometimes the Run button gets disabled on the XAFS_scan plan after a while 

**To Reproduce**
1. Open firefly
2. use it for long time
3. open XAFS_scan
4. run button is diabled
5. Then we restart Firefly, this will fix it

**Other info**
I checked the XAFS_scan in designer, it has the same queue button just like any other plan window

**Comment by Cathyhjj** [comment]
I think this is due to closed environment, which disables the run button, so I'll close this issue

**Comment by canismarko** [comment]
I have an open PR with some improvements to firefly's queue client, hopefully that will help.
